// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPV_Backend.Data;

#nullable disable

namespace ProjetoPV_Backend.Migrations
{
    [DbContext(typeof(ProjetoPV_BackendContext))]
    [Migration("20220320022012_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoPV_Backend.Models.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoriaId"), 1L, 1);

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1L,
                            ClienteId = 0L,
                            Descricao = "Categoria destinada a gastos com transportes.",
                            Nome = "Transportes"
                        },
                        new
                        {
                            CategoriaId = 2L,
                            ClienteId = 0L,
                            Descricao = "Categoria destinada a gastos com alimentação.",
                            Nome = "Comida e Bebida"
                        },
                        new
                        {
                            CategoriaId = 3L,
                            ClienteId = 0L,
                            Descricao = "Categoria destinada a gastos no supermercado.",
                            Nome = "Supermercado"
                        },
                        new
                        {
                            CategoriaId = 4L,
                            ClienteId = 0L,
                            Descricao = "Categoria destinada a gastos com a habitação.",
                            Nome = "Habitação"
                        });
                });

            modelBuilder.Entity("ProjetoPV_Backend.Models.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClienteId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ProjetoPV_Backend.Models.TipoConta", b =>
                {
                    b.Property<long>("TipoContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TipoContaId"), 1L, 1);

                    b.Property<int>("Descricao")
                        .HasColumnType("int");

                    b.HasKey("TipoContaId");

                    b.ToTable("TipoConta");

                    b.HasData(
                        new
                        {
                            TipoContaId = 1L,
                            Descricao = 0
                        },
                        new
                        {
                            TipoContaId = 2L,
                            Descricao = 1
                        },
                        new
                        {
                            TipoContaId = 3L,
                            Descricao = 3
                        },
                        new
                        {
                            TipoContaId = 4L,
                            Descricao = 2
                        },
                        new
                        {
                            TipoContaId = 5L,
                            Descricao = 8
                        },
                        new
                        {
                            TipoContaId = 6L,
                            Descricao = 9
                        },
                        new
                        {
                            TipoContaId = 7L,
                            Descricao = 7
                        },
                        new
                        {
                            TipoContaId = 8L,
                            Descricao = 6
                        },
                        new
                        {
                            TipoContaId = 9L,
                            Descricao = 5
                        },
                        new
                        {
                            TipoContaId = 10L,
                            Descricao = 4
                        });
                });

            modelBuilder.Entity("ProjetoPV_Backend.Models.TipoTransacao", b =>
                {
                    b.Property<long>("TipoTransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TipoTransacaoId"), 1L, 1);

                    b.Property<int>("Descricao")
                        .HasColumnType("int");

                    b.HasKey("TipoTransacaoId");

                    b.ToTable("TipoTransacao");

                    b.HasData(
                        new
                        {
                            TipoTransacaoId = 1L,
                            Descricao = 0
                        },
                        new
                        {
                            TipoTransacaoId = 2L,
                            Descricao = 1
                        },
                        new
                        {
                            TipoTransacaoId = 3L,
                            Descricao = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
